
pipeline {
    agent any

    stages { 
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Image') {
            steps {
                script {
                     sh "docker compose up -d --build"
                    }
                } 
            } 
        stage('Test') { 
            steps { echo 'Running tests...' } }
        stage('Deploy') { 
            steps { echo 'Deploying...' } }
    }

   /*  environment {
        MINIKUBE_HOME = '/tmp/.minikube'
        KUBECONFIG = '/tmp/.kube/config'
    } */
    //stages {
        /* stage('Check Java Version') {
            steps {
                sh 'java -version'
            }
        }
        stage('Check Maven Version') {
            steps {
                sh 'mvn -version'
            }
        }

        stage('Verify Workspace') {
            steps {
                sh 'pwd && ls -al'
            }
        } */

        /* stage('Set up MySQL') {
           steps {
            script {
                sh 'sudo docker-compose -f ./docker/compose.yaml up -d'
               }
            }
        } */
       /*  stage('Build') {
            steps {
                sh './scripts/build.sh'
            }
        } */
        /* stage('Test') {
            steps {
                sh './scripts/test.sh'
            }
        } */
        /* stage('List Files') {
            steps {
                script {
                    sh 'ls -al ./target'
                    }
            }
        } */
        /* stage('Docker Build') {
            steps {
                sh 'docker build -t my-crm-service:latest -f ./docker/Dockerfile .'
            }
        } */
       /*  stage('List Files 2') {
            steps {
                script {
                    sh 'ls -al ./target'
                    }
            }
        } */
        /* stage('Tag Docker Image') {
            steps {
                script {
                    // Agora a imagem deve existir e o comando de tag deve funcionar
                    sh 'docker tag my-crm-service:latest joabio/my-crm-service:latest'
                }
            }
        } */
        /* stage('Login Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
                }
            }
        } */
        /* stage('Push Docker Image') {
            steps {
                sh 'set -x && docker push joabio/my-crm-service:latest'
            }
        } */
        /* stage('Deploy to Kubernetes') {
            steps {
                sh './scripts/deploy.sh'
            }
        } */
    //}
}
